### ISSUE TITLE
How is this code licensed?

### ISSUE THREAD

**Issue by dal00** [axelhjalm/bitwig-midi-fighter-twister#2]
Hi Axel!
Which license this code is licensed under?

I would suggest GPL3 or LGPL3 :)

**Comment by axelhjalm** [comment]
Hi!

I haven't given it any thought yet, but it's meant to be free. I'm at
JavaOne at the moment and won't be able to work on this until next week. I
really only put a few hours into this when I got the twister but will be
happy for any contributions/ideas!

/Axel

Den 5 okt 2017 11:00 skrev "dal00" <notifications@github.com>:

**Comment by dal00** [comment]
Cool! I just got mine and I really like it. 
Unfortunately my java is very rusty so not sure how much I will be able to contribute. But this might be a good time to learn.  :)
Have fun at JavaOne!
