### ISSUE TITLE
Create a release on github with the binary attached

### ISSUE THREAD

**Issue by dal00** [axelhjalm/bitwig-midi-fighter-twister#5]
Github has a release feature where you can publish a binary separately from the repo.
Would be nice to use that and just link to it from the README

It is very easy to set up and releases are based on git tags, so just tag 0.1 or something like that. This is how they work:
https://help.github.com/articles/creating-releases/

Also would be nice if the binary was permanently removed form the git repo because it would make it nicer and smaller to clone. We don't want all new binary releases to add up to a large repo as binaries are not really suited for git.

Some info on how to do that: 
https://itextpdf.com/blog/how-completely-remove-file-git-repository

**Comment by axelhjalm** [comment]
fixed
